// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"dx/internal/adapters/certificate_authority"
	"dx/internal/adapters/command_runner"
	"dx/internal/adapters/container_image_repository"
	"dx/internal/adapters/container_orchestrator"
	"dx/internal/adapters/filesystem"
	"dx/internal/adapters/keyring"
	"dx/internal/adapters/kustomize"
	"dx/internal/adapters/scm"
	"dx/internal/adapters/symmetric_encryptor"
	"dx/internal/adapters/templater"
	"dx/internal/adapters/terminal"
	"dx/internal/core"
	"dx/internal/core/handler"
	"dx/internal/ports"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InjectConfigRepo() (core.ConfigRepository, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	return fileSystemConfigRepository, nil
}

func InjectSecretRepository() (core.SecretsRepository, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	return secretsRepository, nil
}

func InjectBuildCommandHandler() (handler.BuildCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	osCommandRunner := command_runner.ProvideOsCommandRunner()
	gitClient := scm.ProvideGitClient(osCommandRunner, osFileSystem)
	git := scm.ProvideGit(gitClient, osFileSystem)
	dockerRepository := container_image_repository.ProvideDockerRepository(fileSystemConfigRepository, secretsRepository, portsTemplater, osCommandRunner)
	buildCommandHandler := handler.ProvideBuildCommandHandler(fileSystemConfigRepository, git, dockerRepository)
	return buildCommandHandler, nil
}

func InjectInstallCommandHandler() (handler.InstallCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	osCommandRunner := command_runner.ProvideOsCommandRunner()
	dockerRepository := container_image_repository.ProvideDockerRepository(fileSystemConfigRepository, secretsRepository, portsTemplater, osCommandRunner)
	helmClient := container_orchestrator.ProvideHelmClient(osCommandRunner)
	client := kustomize.ProvideKustomizeClient(osCommandRunner, osFileSystem)
	chartWrapper := core.ProvideChartWrapper(osFileSystem)
	kubernetes, err := container_orchestrator.ProvideKubernetes(fileSystemConfigRepository, secretsRepository, portsTemplater, osFileSystem, helmClient, client, chartWrapper)
	if err != nil {
		return handler.InstallCommandHandler{}, err
	}
	devProxyConfigGenerator := core.ProvideDevProxyConfigGenerator()
	devProxyManager := core.ProvideDevProxyManager(fileSystemConfigRepository, osFileSystem, dockerRepository, kubernetes, devProxyConfigGenerator)
	environmentEnsurer := core.ProvideEnvironmentEnsurer(fileSystemConfigRepository, kubernetes)
	gitClient := scm.ProvideGitClient(osCommandRunner, osFileSystem)
	git := scm.ProvideGit(gitClient, osFileSystem)
	x509CertificateAuthority := certificate_authority.ProvideX509CertificateAuthority(osFileSystem, aesGcmEncryptor)
	certificateProvisioner := core.ProvideCertificateProvisioner(x509CertificateAuthority, kubernetes, portsKeyring, aesGcmEncryptor)
	installCommandHandler := handler.ProvideInstallCommandHandler(fileSystemConfigRepository, dockerRepository, kubernetes, devProxyManager, environmentEnsurer, git, certificateProvisioner)
	return installCommandHandler, nil
}

func InjectUninstallCommandHandler() (handler.UninstallCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	osCommandRunner := command_runner.ProvideOsCommandRunner()
	helmClient := container_orchestrator.ProvideHelmClient(osCommandRunner)
	client := kustomize.ProvideKustomizeClient(osCommandRunner, osFileSystem)
	chartWrapper := core.ProvideChartWrapper(osFileSystem)
	kubernetes, err := container_orchestrator.ProvideKubernetes(fileSystemConfigRepository, secretsRepository, portsTemplater, osFileSystem, helmClient, client, chartWrapper)
	if err != nil {
		return handler.UninstallCommandHandler{}, err
	}
	environmentEnsurer := core.ProvideEnvironmentEnsurer(fileSystemConfigRepository, kubernetes)
	dockerRepository := container_image_repository.ProvideDockerRepository(fileSystemConfigRepository, secretsRepository, portsTemplater, osCommandRunner)
	devProxyConfigGenerator := core.ProvideDevProxyConfigGenerator()
	devProxyManager := core.ProvideDevProxyManager(fileSystemConfigRepository, osFileSystem, dockerRepository, kubernetes, devProxyConfigGenerator)
	uninstallCommandHandler := handler.ProvideUninstallCommandHandler(fileSystemConfigRepository, kubernetes, environmentEnsurer, devProxyManager)
	return uninstallCommandHandler, nil
}

func InjectGenEnvKeyCommandHandler() (handler.GenEnvKeyCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	osCommandRunner := command_runner.ProvideOsCommandRunner()
	helmClient := container_orchestrator.ProvideHelmClient(osCommandRunner)
	client := kustomize.ProvideKustomizeClient(osCommandRunner, osFileSystem)
	chartWrapper := core.ProvideChartWrapper(osFileSystem)
	kubernetes, err := container_orchestrator.ProvideKubernetes(fileSystemConfigRepository, secretsRepository, portsTemplater, osFileSystem, helmClient, client, chartWrapper)
	if err != nil {
		return handler.GenEnvKeyCommandHandler{}, err
	}
	genEnvKeyCommandHandler := handler.ProvideGenEnvKeyCommandHandler(fileSystemConfigRepository, osFileSystem, kubernetes)
	return genEnvKeyCommandHandler, nil
}

func InjectContextCommandHandler() (handler.ContextCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	osCommandRunner := command_runner.ProvideOsCommandRunner()
	gitClient := scm.ProvideGitClient(osCommandRunner, osFileSystem)
	git := scm.ProvideGit(gitClient, osFileSystem)
	dockerRepository := container_image_repository.ProvideDockerRepository(fileSystemConfigRepository, secretsRepository, portsTemplater, osCommandRunner)
	contextCommandHandler := handler.ProvideContextCommandHandler(fileSystemConfigRepository, git, dockerRepository)
	return contextCommandHandler, nil
}

func InjectInitializeCommandHandler() (handler.InitializeCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	initializeCommandHandler := handler.ProvideInitializeCommandHandler(fileSystemConfigRepository)
	return initializeCommandHandler, nil
}

func InjectSecretCommandHandler() (handler.SecretCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	terminalInput := terminal.ProvideTerminalInput()
	secretCommandHandler := handler.ProvideSecretCommandHandler(secretsRepository, fileSystemConfigRepository, terminalInput)
	return secretCommandHandler, nil
}

func InjectRunCommandHandler() (handler.RunCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	osCommandRunner := command_runner.ProvideOsCommandRunner()
	gitClient := scm.ProvideGitClient(osCommandRunner, osFileSystem)
	git := scm.ProvideGit(gitClient, osFileSystem)
	runCommandHandler := handler.ProvideRunCommandHandler(fileSystemConfigRepository, secretsRepository, portsTemplater, git, osCommandRunner)
	return runCommandHandler, nil
}

func InjectShowVarsCommandHandler() (handler.ShowVarsCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	showVarsCommandHandler := handler.ProvideShowVarsCommandHandler(secretsRepository, fileSystemConfigRepository)
	return showVarsCommandHandler, nil
}

func InjectGenerateCommandHandler() (handler.GenerateCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	generateCommandHandler := handler.ProvideGenerateCommandHandler(fileSystemConfigRepository)
	return generateCommandHandler, nil
}

func InjectPullCommandHandler() (handler.PullCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	osCommandRunner := command_runner.ProvideOsCommandRunner()
	dockerRepository := container_image_repository.ProvideDockerRepository(fileSystemConfigRepository, secretsRepository, portsTemplater, osCommandRunner)
	terminalInput := terminal.ProvideTerminalInput()
	pullCommandHandler := handler.ProvidePullCommandHandler(fileSystemConfigRepository, dockerRepository, terminalInput)
	return pullCommandHandler, nil
}

func InjectCACommandHandler() (handler.CACommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	x509CertificateAuthority := certificate_authority.ProvideX509CertificateAuthority(osFileSystem, aesGcmEncryptor)
	osCommandRunner := command_runner.ProvideOsCommandRunner()
	helmClient := container_orchestrator.ProvideHelmClient(osCommandRunner)
	client := kustomize.ProvideKustomizeClient(osCommandRunner, osFileSystem)
	chartWrapper := core.ProvideChartWrapper(osFileSystem)
	kubernetes, err := container_orchestrator.ProvideKubernetes(fileSystemConfigRepository, secretsRepository, portsTemplater, osFileSystem, helmClient, client, chartWrapper)
	if err != nil {
		return handler.CACommandHandler{}, err
	}
	certificateProvisioner := core.ProvideCertificateProvisioner(x509CertificateAuthority, kubernetes, portsKeyring, aesGcmEncryptor)
	terminalInput := terminal.ProvideTerminalInput()
	environmentEnsurer := core.ProvideEnvironmentEnsurer(fileSystemConfigRepository, kubernetes)
	caCommandHandler := handler.ProvideCACommandHandler(fileSystemConfigRepository, x509CertificateAuthority, certificateProvisioner, terminalInput, environmentEnsurer)
	return caCommandHandler, nil
}

// wire.go:

var Adapter = wire.NewSet(command_runner.ProvideOsCommandRunner, wire.Bind(new(ports.CommandRunner), new(*command_runner.OsCommandRunner)), scm.ProvideGitClient, scm.ProvideGit, wire.Bind(new(ports.Scm), new(*scm.Git)), container_image_repository.ProvideDockerRepository, wire.Bind(new(ports.ContainerImageRepository), new(*container_image_repository.DockerRepository)), container_orchestrator.ProvideHelmClient, wire.Bind(new(ports.HelmClient), new(*container_orchestrator.HelmClient)), kustomize.ProvideKustomizeClient, wire.Bind(new(ports.KustomizeClient), new(*kustomize.Client)), container_orchestrator.ProvideKubernetes, wire.Bind(new(ports.ContainerOrchestrator), new(*container_orchestrator.Kubernetes)), wire.Bind(new(ports.SecretStore), new(*container_orchestrator.Kubernetes)), filesystem.ProvideOsFileSystem, wire.Bind(new(ports.FileSystem), new(*filesystem.OsFileSystem)), keyring.ProvideZalandoKeyring, symmetric_encryptor.ProvideAesGcmEncryptor, wire.Bind(new(ports.SymmetricEncryptor), new(*symmetric_encryptor.AesGcmEncryptor)), templater.ProvideTextTemplater, terminal.ProvideTerminalInput, wire.Bind(new(ports.TerminalInput), new(*terminal.TerminalInput)), certificate_authority.ProvideX509CertificateAuthority, wire.Bind(new(ports.CertificateAuthority), new(*certificate_authority.X509CertificateAuthority)))

// CoreSet provides domain/core dependencies
var CoreSet = wire.NewSet(core.ProvideFileSystemConfigRepository, wire.Bind(new(core.ConfigRepository), new(*core.FileSystemConfigRepository)), core.ProvideDevProxyConfigGenerator, core.ProvideDevProxyManager, core.ProvideEncryptedFileSecretRepository, core.ProvideEnvironmentEnsurer, core.ProvideChartWrapper, core.ProvideCertificateProvisioner)

// CommandHandlerSet combines all sets needed for command handlers
var CommandHandlerSet = wire.NewSet(
	Adapter,
	CoreSet,
)
